build-push

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,7 +32,7 @@ on:
 jobs:
   lint:
     # to ignore builds on release
-    if: ${{ (github.event.ref_type == 'tag') }}
+    if: ${{ (github.event.ref_type != 'tag') }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -43,6 +43,12 @@ jobs:
         with:
           go-version: 1.14.5
 
+      - name: install golangci-lint
+        run: make install-golangci-lint
+
+      - name: Lint Check
+        run: make golint
+
       - name: Shellcheck
         uses: reviewdog/action-shellcheck@v1
         with:
@@ -52,15 +58,9 @@ jobs:
           pattern: '*.sh'
           exclude: './.git/*,./vendor/*'
 
-      - name: install golangci-lint
-        run: make install-golangci-lint
-
-      - name: Lint checks
-        run: make golint
-
   unit-test:
     # to ignore builds on release
-    if: ${{ (github.event.ref_type == 'tag') }}
+    if: ${{ (github.event.ref_type != 'tag') }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -77,42 +77,41 @@ jobs:
       - name: Upload Coverage Report
         uses: codecov/codecov-action@v3
 
-  bdd-test:
-    needs: ['unit-test']
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-      matrix:
-        kubernetes:
-        - v1.20.15
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  # bdd-test:
+  #   needs: ['unit-test']
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       kubernetes: [v1.20.15]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Set up Go 1.14
-        uses: actions/setup-go@v4
-        with:
-          go-version: 1.14.5
+  #     - name: Set up Go 1.14
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: 1.14.5
 
-      - name: Setup Minikube-Kubernetes
-        uses: manusa/actions-setup-minikube@v2.7.2
-        with:
-          minikube version: v1.30.1
-          kubernetes version: ${{ matrix.kubernetes }}
-          github token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Setup Minikube-Kubernetes
+  #       uses: manusa/actions-setup-minikube@v2.7.2
+  #       with:
+  #         minikube version: v1.30.1
+  #         kubernetes version: ${{ matrix.kubernetes }}
+  #         github token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build images locally
-        run: make lvm-driver-image || exit 1;
+  #     - name: Build images locally
+  #       run: make lvm-driver-image || exit 1;
 
-      - name: bootstrap
-        run: make bootstrap
+  #     - name: bootstrap
+  #       run: make bootstrap
 
-      - name: Running tests
-        run: ./ci/ci-test.sh
+  #     - name: Running tests
+  #       run: ./ci/ci-test.sh
 
   ansible:
     runs-on: ubuntu-latest
-    needs: ['lint', 'unit-test', 'bdd-test']
+    needs: ['lint', 'unit-test']  #, 'bdd-test']
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -140,6 +139,7 @@ jobs:
             ${{ env.IMAGE_ORG }}/lvm-localpv-e2e:ci
 
   csi-driver:
+    permissions: write-all
     runs-on: ubuntu-latest
     needs: ['lint', 'unit-test', 'bdd-test']
     steps:
@@ -172,9 +172,9 @@ jobs:
         uses: crazy-max/ghaction-docker-meta@v4
         with:
           # add each registry to which the image needs to be pushed here
+          # quay.io/${{ env.IMAGE_ORG }}/lvm-driver
           images: |
             ${{ env.IMAGE_ORG }}/lvm-driver
-            quay.io/${{ env.IMAGE_ORG }}/lvm-driver
             ghcr.io/${{ env.IMAGE_ORG }}/lvm-driver
           tag-latest: false
           tag-custom-only: true
@@ -203,12 +203,12 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Login to Quay
-        uses: docker/login-action@v2
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
+      #- name: Login to Quay
+      #  uses: docker/login-action@v2
+      #  with:
+      #    registry: quay.io
+      #    username: ${{ secrets.QUAY_USERNAME }}
+      #    password: ${{ secrets.QUAY_TOKEN }}
 
       - name: Login to GHCR
         uses: docker/login-action@v2
